### ISSUE TITLE
Expose the Pool object?

### ISSUE THREAD

**Issue by s-ahuja** [swansonk14/p_tqdm#4]
this will allow to get pool object's details such as processid etc.

**Comment by swansonk14** [comment]
This would require a bit of work since the underlying p_tqdm objects are iterators which don't provide easy access to the internal pool object. However, I'll see if it's possible to rewrite the p_tqdm objects as classes so that might it might be possible to access internals like the pool object.

**Comment by swansonk14** [comment]
I think it's unlikely that I'll end up writing the code to expose the pool object, but if you want to give it a try, feel free to send a PR and I can take a look.
