### ISSUE TITLE
When using p_tqdm in a Jupyter session and the cell is killed, the processes continue.

### ISSUE THREAD

**Issue by r-menezes** [swansonk14/p_tqdm#46]
p_tqdm is the easiest and most beautiful way to parallelize computations.
I use it often but sometimes I need to cancel some calculation. When this happens, I need to restart the kernel.

I thought that encapsulating the usage of the Pool in a `with ... as ...` clause could solve this problem.
I am presenting a PR implementing this small change to demonstrate it.

**Comment by swansonk14** [comment]
This is now solved by https://github.com/swansonk14/p_tqdm/pull/47. Thank you @r-menezes!
