### ISSUE TITLE
Support tqdm(..., desc='Put description here')

### ISSUE THREAD

**Issue by theHamsta** [swansonk14/p_tqdm#5]
Thanks for writing this awesome library!

It would be nice if the `desc` argument of tqdm would be propagated when using `p_tqdm.p_map(..., desc='My awesome parallel task')` to the internal call of `tqdm`.

**Comment by swansonk14** [comment]
Thank you! And thank you for the suggestion! This functionality is now covered by https://github.com/swansonk14/p_tqdm/pull/2, which allows any `kwargs` to be passed to the tqdm object.

**Comment by ahmedbesbes** [comment]
Hello! Thanks for the great package and this feature.
I was wondering if the description could be updated dynamically? I'm trying to change its value (to reflect the number of scraped items so far )but the description is stuck at the initial value.
thanks

Here's what I've tried so far: 
```python   

all_posts = []
all_tags = []
n = 0

progress_bar = p_uimap(
    extract_page, days, **{"num_cpus": args.num_cpus, "desc": f"n = {n}"},
)

for posts_by_page, tags_by_page in progress_bar:
    all_posts += posts_by_page
    all_tags += tags_by_page

    n += len(all_posts)
```
